[project]
name = "elexonapi"
version = "0.1.0"
description = "Lightweight Python client for the Elexon BMRS Insights API."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "itables>=2.6.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
